### Notebook 2

In [ ]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df= pd.read_csv("summer-products-with-rating-and-performance_2020-08.csv")
df.head()

,title,title_orig,price,retail_price,currency_buyer,units_sold,uses_ad_boosts,rating,rating_count,rating_five_count,...,merchant_rating_count,merchant_rating,merchant_id,merchant_has_profile_picture,merchant_profile_picture,product_url,product_picture,product_id,theme,crawl_month
0,2020 Summer Vintage Flamingo Print Pajamas Se...,2020 Summer Vintage Flamingo Print Pajamas Se...,16.00,14,EUR,100,0,3.76,54,26.0,...,568,4.128521,595097d6a26f6e070cb878d1,0,NaN,https://www.wish.com/c/5e9ae51d43d6a96e303acdb0,https://contestimg.wish.com/api/webimage/5e9ae...,5e9ae51d43d6a96e303acdb0,summer,2020-08
1,SSHOUSE Summer Casual Sleeveless Soirée Party ...,Women's Casual Summer Sleeveless Sexy Mini Dress,8.00,22,EUR,20000,1,3.45,6135,2269.0,...,17752,3.899673,56458aa03a698c35c9050988,0,NaN,https://www.wish.com/c/58940d436a0d3d5da4e95a38,https://contestimg.wish.com/api/webimage/58940...,58940d436a0d3d5da4e95a38,summer,2020-08
2,2020 Nouvelle Arrivée Femmes Printemps et Été ...,2020 New Arrival Women Spring and Summer Beach...,8.00,43,EUR,100,0,3.57,14,5.0,...,295,3.989831,5d464a1ffdf7bc44ee933c65,0,NaN,https://www.wish.com/c/5ea10e2c617580260d55310a,https://contestimg.wish.com/api/webimage/5ea10...,5ea10e2c617580260d55310a,summer,2020-08
3,Hot Summer Cool T-shirt pour les femmes Mode T...,Hot Summer Cool T Shirt for Women Fashion Tops...,8.00,8,EUR,5000,1,4.03,579,295.0,...,23832,4.020435,58cfdefdacb37b556efdff7c,0,NaN,https://www.wish.com/c/5cedf17ad1d44c52c59e4aca,https://contestimg.wish.com/api/webimage/5cedf...,5cedf17ad1d44c52c59e4aca,summer,2020-08
4,Femmes Shorts d'été à lacets taille élastique ...,Women Summer Shorts Lace Up Elastic Waistband ...,2.72,3,EUR,100,1,3.10,20,6.0,...,14482,4.001588,5ab3b592c3911a095ad5dadb,0,NaN,https://www.wish.com/c/5ebf5819ebac372b070b0e70,https://contestimg.wish.com/api/webimage/5ebf5...,5ebf5819ebac372b070b0e70,summer,2020-08

In [3]:
categoric_Var=[]
discret_var=[]
Continues_vars= []

for colname in df.columns:
    if(df[colname].dtype == 'object'):
        categoric_Var.append(colname)
    else:
        cantidad_valores = len(df[colname].value_counts())
        if(cantidad_valores<=30):
            discret_var.append(colname)
        else:
            Continues_vars.append(colname)

In [4]:
dfcategoric_var = pd.DataFrame(df, columns = categoric_Var)
dfdiscret_var = pd.DataFrame(df, columns = discret_var)
dfcontinuos_var = pd.DataFrame(df, columns = Continues_vars)

In [11]:
df_transformado = df[['origin_country','product_variation_size_id','urgency_text','price','retail_price','rating','merchant_rating','units_sold','uses_ad_boosts','badge_product_quality']].copy()
df_transformado

,origin_country,product_variation_size_id,urgency_text,price,retail_price,rating,merchant_rating,units_sold,uses_ad_boosts,badge_product_quality
0,CN,M,Quantité limitée !,16.00,14,3.76,4.128521,100,0,0
1,CN,XS,Quantité limitée !,8.00,22,3.45,3.899673,20000,1,0
2,CN,XS,Quantité limitée !,8.00,43,3.57,3.989831,100,0,0
3,CN,M,NaN,8.00,8,4.03,4.020435,5000,1,0
4,CN,S,Quantité limitée !,2.72,3,3.10,4.001588,100,1,0
...,...,...,...,...,...,...,...,...,...,...
1568,CN,S,NaN,6.00,9,4.08,4.224605,10000,1,0
1569,CN,S,Quantité limitée !,2.00,56,3.07,3.696054,100,1,0
1570,CN,SIZE S,NaN,5.00,19,3.71,3.961905,100,0,0
1571,CN,Size S.,NaN,13.00,11,2.50,3.774194,100,0,0
1572,CN,S,NaN,7.00,6,4.07,4.235939,100,1,0

In [13]:
def getNanColNames(df):
    colnames = df.columns
    cols_con_na = []
    for col in colnames:
        if(df[col].isnull().sum() > 0):
            cols_con_na.append(col)
    return cols_con_na
cols_con_nan = getNanColNames(df_transformado)
cols_con_nan
df_transformado[cols_con_nan].isnull().mean()

origin_country               0.010807
product_variation_size_id    0.008900
urgency_text                 0.699301
dtype: float64

In [16]:

df_transformado["product_variation_size_id"].value_counts()

S                      641
XS                     356
M                      200
XXS                    100
L                       49
                      ...
6XL                      1
AU plug Low quality      1
XXXL                     1
25-S                     1
SIZE S                   1
Name: product_variation_size_id, Length: 106, dtype: int64

In [17]:
df_transformado["origin_country"].value_counts()

CN    1516
US      31
VE       5
SG       2
AT       1
GB       1
Name: origin_country, dtype: int64

In [18]:
df_transformado['urgency_text'].fillna('no', inplace=True)
df_transformado['origin_country'].fillna('CN', inplace=True)
df_transformado['product_variation_size_id'].fillna('S', inplace=True)

In [19]:
df_transformado[cols_con_nan].isnull().mean()

origin_country               0.0
product_variation_size_id    0.0
urgency_text                 0.0
dtype: float64

In [20]:
def executeFreqEncoding(df, map_type='freq'):
    colnames = df.columns
    for col in colnames:
        if(df[col].dtype == 'object'):
            factor_div = 1 if (map_type == 'freq') else len(df[col])
            mapper = (df[col].value_counts().sort_values(ascending=False)/factor_div).to_dict()
            df[col] = df[col].map(mapper)

In [21]:
executeFreqEncoding(df_transformado)
df_transformado

,origin_country,product_variation_size_id,urgency_text,price,retail_price,rating,merchant_rating,units_sold,uses_ad_boosts,badge_product_quality
0,1533.0,200.0,472.0,16.00,14,3.76,4.128521,100,0,0
1,1533.0,356.0,472.0,8.00,22,3.45,3.899673,20000,1,0
2,1533.0,356.0,472.0,8.00,43,3.57,3.989831,100,0,0
3,1533.0,200.0,1100.0,8.00,8,4.03,4.020435,5000,1,0
4,1533.0,655.0,472.0,2.72,3,3.10,4.001588,100,1,0
...,...,...,...,...,...,...,...,...,...,...
1568,1533.0,655.0,1100.0,6.00,9,4.08,4.224605,10000,1,0
1569,1533.0,655.0,472.0,2.00,56,3.07,3.696054,100,1,0
1570,1533.0,1.0,1100.0,5.00,19,3.71,3.961905,100,0,0
1571,1533.0,2.0,1100.0,13.00,11,2.50,3.774194,100,0,0
1572,1533.0,655.0,1100.0,7.00,6,4.07,4.235939,100,1,0

In [22]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(df_transformado)

StandardScaler()

In [23]:
dataset_final = pd.DataFrame(scaler.transform(df_transformado), columns=df_transformado.columns)
np.round(dataset_final.describe(), 2)
corr_matrix = dataset_final.corr(method='pearson')
corr_matrix

,origin_country,product_variation_size_id,urgency_text,price,retail_price,rating,merchant_rating,units_sold,uses_ad_boosts,badge_product_quality
origin_country,1.000000,0.017956,0.017123,-0.022855,-0.024394,0.035976,0.019702,0.046757,-0.038606,-0.015519
product_variation_size_id,0.017956,1.000000,-0.006697,0.030748,0.085524,-0.034041,0.009884,0.068455,-0.117810,0.020099
urgency_text,0.017123,-0.006697,1.000000,0.022135,0.011574,0.037445,-0.002240,0.023205,-0.018559,0.011794
price,-0.022855,0.030748,0.022135,1.000000,0.304748,0.053469,0.047121,-0.024815,-0.073269,0.009512
retail_price,-0.024394,0.085524,0.011574,0.304748,1.000000,0.024106,0.054399,0.012638,-0.035325,0.000098
rating,0.035976,-0.034041,0.037445,0.053469,0.024106,1.000000,0.237305,0.039478,-0.049410,0.264360
merchant_rating,0.019702,0.009884,-0.002240,0.047121,0.054399,0.237305,1.000000,0.122504,-0.022564,0.191399
units_sold,0.046757,0.068455,0.023205,-0.024815,0.012638,0.039478,0.122504,1.000000,-0.016055,0.063187
uses_ad_boosts,-0.038606,-0.117810,-0.018559,-0.073269,-0.035325,-0.049410,-0.022564,-0.016055,1.000000,0.001697
badge_product_quality,-0.015519,0.020099,0.011794,0.009512,0.000098,0.264360,0.191399,0.063187,0.001697,1.000000

In [25]:
dataset_final.to_csv('C:/Users/jamm_/Documents/Proyecto2staticallearning/dataset_final.csv',index=False)